### ISSUE TITLE
move results to submenus under results menu

### ISSUE THREAD

**Issue by mdscheuerell** [markusmin/steelhead#3]
I think the website would be easier to read/navigate if you moved each of the results set to its own submenu under a general "Results" tab. To do so, change [these lines](https://github.com/markusmin/steelhead/blob/e4c5019c4276ffaf9e15ad5f33c9f5308e35e6e2/docs/_site.yml#L12-L25) in `_site.yml`:
```
    - text: "Results - detection efficiency"
      href: results-detection-efficiency.html   
    - text: "Results - final fates"
      href: results-final-fates.html   
    - text: "Results - temperature"
      href: results-temperature.html   
    - text: "Results - winter spill days"
      href: results-spill-days.html    
    - text: "Results - spill volume"
      href: results-spill-window.html    
    - text: "Results - interannual differences"
      href: results-year.html    
    - text: "Results - final fates and covariates"
      href: results-final-fates-covariates.html    
```
to something like this:
```
    - text: "Results"
      menu:  
      - text: "Detection efficiency"
        href: results-detection-efficiency.html   
      - text: "Final fates"
        href: results-final-fates.html   
      - text: "Temperature"
        href: results-temperature.html   
      - text: "Winter spill days"
        href: results-spill-days.html    
      - text: "Spill volume"
        href: results-spill-window.html    
      - text: "Interannual differences"
        href: results-year.html    
      - text: "Final fates and covariates"
        href: results-final-fates-covariates.html    
```
